from enum import Enum

class COARSE_GRAINED_INTENT(Enum):
    INFO_REQUIRING = 'INFO_REQUIRING'
    INFO_PROVIDING = 'INFO_PROVIDING'
    ACTION_REQUESTING = 'ACTION_REQUESTING'

class FINE_GRAINED_INTENT(Enum):
    SQL_QUERY = 'SQL_QUERY'
    VECTOR_QUERY = 'VECTOR_QUERY'
    PROACTIVELY_INFORM = 'PROACTIVELY_INFORM'
    REPLY_INFORM = 'REPLY_INFORM'
    REPLY_DONT_KNOW = 'REPLY_DONT_KNOW'
    REPLY_ACCEPT = 'REPLY_ACCEPT'
    REPLY_REFUSE = 'REPLY_REFUSE'
    REPLY_ACK = 'REPLY_ACK'
    REPLY_AFFIRM = 'REPLY_AFFIRM'
    REPLY_DENY = 'REPLY_DENY'
    REPLY_FINISH = 'REPLY_FINISH'
    REPLY_NOT_FINISH = 'REPLY_NOT_FINISH'
    TASK_START = 'TASK_START'
    TASK_CANCEL = 'TASK_CANCEL'

class Fill_TYPE(Enum):
    COVER = 'COVER'
    APPEND = 'APPEND'
