tb:
  - 咨询
  - 反馈
  - 阐述
  - 确认
  - 解释
  - 请求
  - 接受
  - 问候
  - 闲聊


NLUpp:
  General dialogue acts:
    - name: affirm
      desc: the intent to affirm something
    - name: deny
      desc: the intent to deny something
    - name: dont_know
      desc: the intent to say I don't know
    - name: acknowledge
      desc: the intent to what was said
    - name: greet
      desc: the intent to greet someone
    - name: end_call
      desc: the intent to end call or say goodbye
    - name: thank
      desc: the intent to thank someone
    - name: repeat
      desc: the intent asking someone to repeat something
  Actions:
    - name: cancel_close_leave
      desc: the intent asking about canceling or closing something
    - name: change
      desc: the intent to change or modify something
    - name: make
      desc: the intent to make,open,apply,set up or activate something
  Questions:
    - name: request_info
      desc: the intent to ask or request some information
    - name: how
      desc: the intent asking how to do something
    - name: why
      desc: the intent to ask why something happened or needs to be done
    - name: when
      desc: the intent to ask about when or what time something happens
    - name: how_much
      desc: the intent asking about some quantity or how much
    - name: how_long
      desc: the intent asking about how long something takes
  General_adjectives:
    - name: not_working
      desc: the intent asking about something wrong, missing or not working
    - name: lost_stolen
      desciption: the intent asking about something being lost or stolen
    - name: more_higher_after
      desc: the intent to indicate something more, higher, after or increasing
    - name: less_lower_before
      desc: the intent to indicate something less, lower, before or decreasing
    - name: new
      desc: the intent asking about something new
    - name: existing
      desc: the intent asking about something that already exists
    - name: limits
      desc: the intent asking about some sort of limit